### ISSUE TITLE
Mejorar instrucciones de instalación

### ISSUE THREAD

**Issue by martinszy** [ProjectPODER/QuienEsQuien#2]
- [x] Agregar requerimientos (mongodb y meteor)
- [ ] Agregar comandos de importación de datos

**Comment by kyv** [comment]
Estamos dando seguimiento en #4. El segundo punto complica un poquito: ¿desde donde imaginas que si obtendria una compia del base de datos para poder importarlos?

**Comment by martinszy** [comment]
Deberíamos tener comandos de inicialización de la base vacía y un conjunto de datos iniciales desde el cual se pueda reconstruir el conjunto completo.
Te parece publicar un archivo de base de datos exportada de mongo con unas 1000 filas en cada tabla? Como para que se pueda probar al menos.
Y luego agregar al readme los comandos para importar ese archivo.
O sino tener la base vacía y los comandos para importar al menos algun tipo de dato a la db.

**Comment by kyv** [comment]
Yo opteria para opción uno, poner un base en el web. Pero creo que debemos poner un dump completo del base de datos en el web.

**Comment by martinszy** [comment]
Un dump completo? Y con qué frecuencia se actualizaría?

**Comment by kyv** [comment]
Diario?

**Comment by martinszy** [comment]
Diario actualizado a github? O a nuestros servidores? Habría que crear un script nuevo que automatice eso? Es mucho trabajo?

**Comment by kyv** [comment]
No me gusta la idea de guardar un dump de un DB en github. Menos si es muy pequenisimo. Tus otras preguntas son las mismos preguntas que tengo. Por eso no si ha hecho. ¿Donde opinas tu seria un buen lugar para guardarlo? Si, habra que crear un script. No. No es un gran cantidad de trabajo, pero existen detalles dependiente de donde dicidimos hospedarlo.

**Comment by martinszy** [comment]
no hay una api que nos permita pedir un dump completo de la base que ya tenemos? o crear una cuenta de usuario anónimo en nuestra db y que se descargue de ahi? digo para ahorrarnos el programar

**Comment by kyv** [comment]
No veo problema en hacer el dump. Seria un script muy sencillo en bash. Para mi la mayor duda es donde hospedarlo. Veo estas opciones:

1.    nextcloud
2.   donde esta hospedado el api

1) require elaborar un poco de codigo que utiliza webdav probablamente y establecer un acuerdo acerca de ficheros publicos en nextcloud.
2) require elaborar configuraciones de kubernetes. 

Niguno de los dos es muy dificil. Pero siempre hemos dedicado el tiempo a otros cosas. Mi preferencia es opción 2.

**Comment by martinszy** [comment]
Ok, vamos con 2.
