### ISSUE TITLE
Agregar CI

### ISSUE THREAD

**Issue by kyv** [ProjectPODER/QuienEsQuien#5]
Vamos a integrar alguna sistema de integración continuo. Por el momento estamos considerando *travis* y *circle*.

**Comment by martinszy** [comment]
Acabo de descargar el branch de dev y no compila, quizás esta integración continua debería aplicar al branch de dev también? Podés configurar eso?

**Comment by kyv** [comment]
No hay nada que configurar. Siempre ha sido asi:
https://github.com/ProjectPODER/QuienEsQuien/commits/dev
